### ISSUE TITLE
2.4.0 BUG on Safari 6.2 "undefined is not a function (evaluating 'u.forEach')

### ISSUE THREAD

**Issue by maxsennin** [jhildenbiddle/css-vars-ponyfill#142]
Hello,

I report a bug of css-vars-ponyfill 2.4.0 on Safari 6.2.
I'm using "https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"

It seems like the variable "srcNodes" on line 266 of "index.js" is undefined.

https://github.com/jhildenbiddle/css-vars-ponyfill/blob/8ddc2a6752e3f2e3902fcdaaad89ce48b27c1030/src/index.js#L266

Thank you for your work!! 👍

**Comment by WrathZA** [comment]
Looks to be the same issue as the one I raised earlier in https://github.com/jhildenbiddle/css-vars-ponyfill/issues/141
NodeList API: forEach only supported in >Safari 10 

https://caniuse.com/?search=NodeList%20API%3A%20forEach

I solved quickly by pinning to the `https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2.3.2`

**Comment by maxsennin** [comment]
Ok, I did the same thing.

Thank you :)

(and, as usual, shame on Apple for not updating Safari on all OS...)

**Comment by maxsennin** [comment]
I find a solution to use the version 2.4.0.

I load a polyfill for the NodeList API: forEach
https://polyfill.io/v3/polyfill.min.js?features=NodeList.prototype.forEach

And after that, the version 2.4.0 works on Safari 6.2

**Comment by jhildenbiddle** [comment]
Thanks @maxsennin.

My response to the same issue filed in #141:

> This bug made me realize that my test setup is loading `@babel/preset-env` which is why [all tests were passing](https://travis-ci.org/github/jhildenbiddle/css-vars-ponyfill) instead of throwing an error in IE legacy browsers that don't support `forEach` on node lists.
> 
> Easy fix. I'll release a patch later tonight or tomorrow AM.

Thanks!

**Comment by jhildenbiddle** [comment]
Fixed in 2.4.1
